#!/usr/bin/env python3
"""Write reviewed synthetic story specs; rendering uses the existing thread kit.

This authoring source is not evidence. All additions are fictional, and existing
messages are never rewritten. Dates below are Pacific local time.
"""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
TOM = 'treyes@alderpointpartners.com'
PRIYA = 'pshah@alderpointpartners.com'
HANNAH = 'hcole@cascadetimber.com'
SARAH = 'snguyen@cascadetimber.com'
CRAIG = 'csato@cascadetimber.com'
ROB = 'rdenniston@cascadetimber.com'
JOHN = 'jellery@cascadetimber.com'
JAY = 'jwhitfield@alderpointpartners.com'
DEREK = 'dholt@bellhavenadvisory.com'
ORR = 'jorr@cppension.org'
MOSS = 'bmoss@mosslane-cpa.com'


def message(key, parent, sender, to, date, body, **extra):
    return dict(key=key, parent=parent, kind=extra.pop('kind', 'reply'), **{'from': sender},
                to=to if isinstance(to, list) else [to], date=date, body=body, **extra)


def attachment(filename, content):
    return dict(filename=filename, content=content)


def write(thread, anchor, arc, start, rationale, messages, refs):
    # Inline byte-identical copies of earlier new attachments; thread_kit's
    # from_doc lookup otherwise only supports already-rendered corpus records.
    earlier = {}
    for offset, msg in enumerate(messages):
        resolved = []
        for att in msg.get('attachments', []):
            if att.get('from_doc') in earlier:
                att = next(dict(a) for a in earlier[att['from_doc']]
                           if a['filename'] == att['filename'])
            resolved.append(att)
        if resolved:
            msg['attachments'] = resolved
        earlier['EMAIL-' + str(start + offset)] = resolved
    spec = dict(thread_id=thread, anchor=anchor, arc=arc,
                event_id=thread + '-density-expansion', start_docid=start,
                bible_refs=refs, rationale=rationale, messages=messages)
    path = HERE / (thread + '.json')
    path.write_text(json.dumps(spec, ensure_ascii=False, indent=2) + '\n')
    print(path.name, len(messages), 'messages', 'EMAIL-' + str(start),
          'through EMAIL-' + str(start + len(messages) - 1))


def main():
    write('THR-005', 'EMAIL-1454', 'A', 1475,
          'Follow the three held files without equating them with the original disputed NW parcels. '
          'Records staff obtain missing support, finance separates submission from revenue, and '
          'commercial forecasts outrun release authority. Two files remain unreleased; a third '
          'gets conditional permission for a corrected application, with actual filing still unknown.', [
        message('m1', 'EMAIL-1454', TOM, HANNAH, '2022-11-08T13:40',
                "Hannah — thanks for separating them. To keep the folders straight, I've given the three held files tracking names Q4-H1, Q4-H2 and Q4-H3. Those are queue references, not county numbers, and they aren't the original eight Northwest files.\n\nOn the other two, can you confirm whether the county copies you added actually include the recorded easement exhibit? The cover filings were already there; the missing pieces were the recorded versions of the easement language. I don't want our tracker to say complete if we've only added a second cover sheet. Please leave the three on hold while Priya decides the quarter.", cc=[SARAH]),
        message('m2', 'm1', HANNAH, TOM, '2022-11-09T09:15',
                "Yes, the two copies include the recorded easement exhibit and the map page; I pulled them from our paper files, not the marketing folder. That fills the document gap. It doesn't mean I've reviewed whether the wording meets the program criteria.\n\nFor the three held files, I attached the queue note so everyone has the same references. H1 is an old listing figure against a newer county filing. H2 has two survey areas that may overlap. H3 has a county scan with the acreage line cut off. Those could have different explanations, so I'd rather not use one 'acreage issue' code for all three. Nothing from that subfolder went into yesterday's outgoing batch.", cc=[SARAH],
                attachments=[attachment('Q4_held_queue_2022-11-09.txt',
                    'RECORDS QUEUE NOTE — 9 November 2022\nLocal tracking references only; not parcel IDs. Separate from original NW-01–NW-08.\nQ4-H1 | listing acreage differs from newer county filing | transmittal blank | held\nQ4-H2 | two survey areas may overlap | transmittal blank | held\nQ4-H3 | county scan crops acreage line | transmittal blank | held\nOther six files: outgoing Q4 batch; no conclusion on eligibility or certificate delivery.\nPrepared by Hannah Cole from folder contents.\n')]),
        message('m3', 'm2', SARAH, [HANNAH, TOM], '2022-11-09T11:10',
                "Please leave the queue references on the tracker and keep the old acreage column as well as any proposed correction. We need to see what changed, not just the final number.\n\nFor H1, ask for the source and date of the listing figure. For H2, a marked plan showing the boundary between the two survey areas would answer more than another summary email. For H3, order the full county copy. My packet request was to document differences; it wasn't permission to submit the held files or an eligibility sign-off. Tom, please get Priya to name the person who can release each one. Hannah's records check and our quarterly sample work are separate steps.", kind='reply_all'),
        message('m4', 'm3', TOM, PRIYA, '2022-11-10T08:35',
                "Priya — Sarah's requests are below. H1 needs a dated source, H2 needs a boundary plan and H3 needs the full scan. Hannah has left all three out.\n\nJay's buyer list still assumes nine files and a Thanksgiving certificate run. Could you tell him to use six until we have release instructions? I can chase documents, but I can't give him a delivery date for a file that's still sitting in the hold folder. If you want H1 sent at the county figure instead, please say that explicitly so Hannah and I don't treat a change in the forecast as an instruction to file.", kind='forward', keep_attachments=False),
        message('m5', 'm4', PRIYA, TOM, '2022-11-10T12:20',
                "Keep the commercial forecast at nine for now; it shows the upside if the documents arrive. I'll have Jay distinguish that from what he can offer. We're not committing all nine to a buyer this week.\n\nH1 looks like the quickest fix if the listing sheet is simply old. Please get the owner to acknowledge the county figure before changing the application. H2 needs the plan Sarah asked for. On H3, see whether the recorder can email a legible copy rather than waiting for the mail. I still want a path to November, but I don't want Hannah guessing which acreage to put on a submitted form.", cc=[JAY]),
        message('m6', 'm5', JAY, [PRIYA, TOM], '2022-11-11T10:05',
                "I can show six firm and three conditional in the pipeline sheet. My problem is that buyers don't see those columns; they hear the total on the call and ask for a delivery date. Blue River wants a December allocation and North Fork needs its paperwork before their committee meets.\n\nPlease give me an approved sentence for the conditional three. Until then I'll quote only credits already available for allocation and won't promise these files. The Lane/Klamath easement files and these acreage files are getting mixed together in conversations, so I'd like the county documents attached to the right folders before anyone uses them to answer diligence questions.", kind='reply_all'),
        message('m7', 'm5', TOM, PRIYA, '2022-11-14T14:30',
                "Update after the owner calls. H1's listing was prepared before the easement boundary was narrowed. The owner emailed acceptance of the county figure; the revised application is in the folder alongside the first draft. H2's surveyor says the areas may overlap, but wants the original field notes before drawing a boundary line. H3's complete county copy arrived; it is legible and it still differs from our application.\n\nSo one file has a proposed correction and two need more work. I haven't sent any of the three to Hannah as released. If H1 goes this quarter, the forecast needs the revised figure, not the listing acreage. Please confirm who reviews the corrected form.", cc=[HANNAH]),
        message('m8', 'm7', PRIYA, [TOM, HANNAH], '2022-11-15T09:20',
                "H1 can move on the corrected county figure once Sarah checks the tie-out and Hannah has the owner's acknowledgment in the packet. Please keep both application versions. I'm approving that route, not the original listing acreage.\n\nLeave H2 and H3 out of the outgoing batch until we have reconciliations. Jay can keep them conditional for planning, but they aren't available inventory. Tom, send Craig the revision to the pipeline figure so he isn't modeling all nine at the original amounts. If the H1 paperwork slips past the certificate window, we'll live with Q1 rather than mark it delivered before it is.", kind='reply_all', cc=[SARAH]),
        message('m9', 'm8', HANNAH, [PRIYA, TOM], '2022-11-15T11:45',
                "H1 has the owner email and both application drafts in its folder. Sarah's tie-out is still open, so the release box is blank and I haven't put it in the next courier run. H2 and H3 remain in the separate subfolder. I've attached today's queue note; the November 9 note is retained alongside it.\n\nOne clarification for the system: 'ready for review' and 'submitted' are different statuses. Please don't copy the commercial forecast status into the submission column. The other six have outgoing packet entries, but I don't hold the certificate delivery records, so I can't tell Jay whether they meet his buyer dates.", kind='reply_all', cc=[SARAH, CRAIG],
                attachments=[attachment('Q4_held_queue_2022-11-15.txt',
                    'RECORDS QUEUE NOTE — 15 November 2022\nQ4-H1 | revised to county figure; owner acknowledgment in folder | Sarah tie-out OPEN | release blank; no transmittal\nQ4-H2 | field notes requested for overlap | release blank; no transmittal\nQ4-H3 | full county scan received; discrepancy remains | release blank; no transmittal\nDo not overwrite the 9 November queue note. Commercial forecast is not a submission register.\n')]),
        message('m10', 'm9', CRAIG, HANNAH, '2022-11-16T08:50',
                "Hannah — this is helpful. I've taken H2 and H3 out of the committed Q4 forecast and moved H1 into a separate conditional line. I won't book any of them from a pipeline status. Under our April policy, certificate delivery is what determines revenue, and I need delivery evidence rather than a packet or an issuance date.\n\nCould you keep the transmittal field separate from the delivery field when the tracker goes to Rob? The original Northwest eight already have their own face builds; these queue references must not be added to that schedule just because both sets have acreage questions. I'll ask Alder for delivery support on the six separately.", cc=[ROB]),
        message('m11', 'm10', ROB, [CRAIG, HANNAH], '2022-11-16T10:40',
                "Understood on recognition. Send me the bridge between Priya's commercial forecast and your committed number before Friday. I want to know whether the gap is missing support, a lower acreage input or delivery timing; those mean different things for the year-end call.\n\nKeep H1 conditional until the review box is signed. I don't need an eligibility judgment from finance, but I do need the forecast we show Elena to agree with what people are actually able to submit and deliver. Please leave the earlier forecast in the folder so we can explain the change rather than circulate another file called final.", kind='reply_all'),
        message('m12', 'm9', SARAH, HANNAH, '2022-11-17T15:10',
                "I've checked H1's revised application acreage against the county copy and the owner's acknowledgment. Those figures agree. You can send that corrected version through the normal application route if the rest of the packet checklist is complete; this check covers the acreage tie-out only.\n\nPlease enter the actual transmittal date when it goes, not today's date by default. H2 and H3 stay unreleased. I'll log this as a targeted packet exception check, not as completion of the quarterly sample review. Craig, that distinction needs to survive in the close file: a single corrected file doesn't establish that the framework's quarterly testing was performed.", cc=[TOM, CRAIG]),
    ], ['§0 Q4 warnings [ESTABLISHED]', 'THR-003 / EMAIL-1454 six submitted, three held [ESTABLISHED]',
        '§1 certificate-delivery recognition [ESTABLISHED]', '§6 spot-check performance remains unresolved',
        'Density expansion register §1 [AUTHORED FICTIONAL ADDITIONS]'])

    write('THR-006', 'EMAIL-704', 'C', 1487,
          'Buyer reconciliation joins agreements, source-certificate allocations, actual delivery '
          'and cash. A buyer copy lacks one source-reference page; an initial reconstruction '
          'misallocates NW-07 until a dated register is produced. The three named purchases are '
          'only a subset of annual revenue. Refund entitlement, tax loss and eligibility remain open.', [
        message('m1', 'EMAIL-704', TOM, ORR, '2023-08-14T09:30',
                "J — the signed copy matches our agreement file: November 9, face 1.25 million, unit price 0.90. The batch number in my tracker is unreliable; I'm joining on your purchaser name and agreement date instead.\n\nI'm pulling the delivery emails and the source allocation pages now. Your status question is fair, and the July pause note didn't answer it. We need to distinguish a certificate we issued from one we actually transmitted to you. Could you send the list your custodian has, including any missing source pages? I'll reconcile your copy with ours rather than tell you everything was delivered from a 'closed' box on our tracker.", cc=[DEREK]),
        message('m2', 'm1', ORR, TOM, '2023-08-14T13:15',
                "Tom — our custodian's receipt log shows one secure delivery on November 16 for 1.25 million face. The source list has NW-03 at 620,000 and NW-02 at 520,000. The remaining 110,000 has a certificate reference but no source parcel on the page in our saved set.\n\nWe had the May eligibility checklist in the committee packet and understood the signed representation to cover all of the purchased credits. This request isn't a statement that we have a disallowance notice; we don't. We want a complete source list and a factual status before the committee meets. Please identify which page is missing rather than sending the whole approved kit again.", cc=[DEREK],
                attachments=[attachment('CPP_custodian_receipt_extract_2023-08-14.txt',
                    'CPP CUSTODIAN RECEIPT EXTRACT — 14 August 2023\nPurchase agreement effective 9 November 2022.\nSecure delivery received 16 November 2022, 14:06 PT; aggregate face 1,250,000.\nSaved source entries: NW-03 620,000; NW-02 520,000; final entry 110,000 source parcel page missing in saved copy.\nThis is a purchaser receipt-log extract, not an eligibility determination. No disallowance notice recorded here.\n')]),
        message('m3', 'm2', DEREK, [ORR, TOM], '2023-08-15T10:10',
                "J — I've found our settlement entry for your November 9 funding: 1,125,000 cash against 1,250,000 face. That ties to the signed price, not the earlier 0.89 draft. It doesn't answer the missing source page. Tom's team maintains those allocations.\n\nOur intake sheet says delivery complete because it carries Alder's completion date. It is not a receipt from your custodian, and I'm not relying on it to say what you actually received. Tom, please send the allocation directly to J with the date of the source record. I'd also like the same list in our file so we stop answering from different versions.", kind='reply_all'),
        message('m4', 'm2', TOM, CRAIG, '2023-08-15T14:20',
                "Craig — CPP's receipt extract is below. We need the missing 110,000 source page and a clean link between the source certificates and the buyer schedule. Can you reconcile that without using my batch numbers?\n\nFor the other two signed purchases, I've pulled North Fork at 900,000 face on November 21 and Blue River at 1.1 million on December 6. My working allocation puts some NW-07 into CPP, but I don't trust that line; the sheet was copied from an earlier reservation list. Please don't use it as the delivery register. I'm asking for ordinary transaction support, not counsel's exposure workbook.", kind='forward', keep_attachments=False, cc=[HANNAH]),
        message('m5', 'm4', CRAIG, TOM, '2023-08-16T09:05',
                "The contract totals tie, but your NW-07 reservation line doesn't. The source certificate is 560,000 face, and your draft allocates more than that across the buyers. Please send the dated final register rather than adjust the overage by moving a number to another parcel.\n\nI can reconcile funding from the settlements and delivery from receipts. Neither record proves the underlying acreage was correct. Also, my May full-parcel schedule wasn't buyer-specific, and the excess-acreage tab is still separate legal work. We shouldn't answer CPP's document request with an allocation reverse-engineered from an exposure ceiling. Hannah, can you check the certificate references on the copy Tom sends?", cc=[HANNAH]),
        message('m6', 'm5', TOM, [CRAIG, HANNAH], '2023-08-16T15:40',
                "Found the dated delivery register in the November/December administration archive. Attached is a text export of just these three purchases. It places CPP's final 110,000 against NW-01, not NW-07. My reservation sheet predates the November 15 NW-07 issuance and should not have been used as the final list.\n\nNW-07 is split between North Fork and Blue River in the register. Please check the sum against the source certificate before I send buyer-specific extracts. The export references source certificates rather than creating new certificate numbers for each slice. I've left the original reservation sheet in the folder and marked it superseded, so the mismatch remains explainable.", kind='reply_all',
                attachments=[attachment('Three_purchase_delivery_register_export_2023-08-16.txt',
                    'ALDER ADMINISTRATION ARCHIVE — three-purchase delivery register extract\nExported 16 August 2023. Source: dated November/December 2022 delivery register.\nBuyer | Agreement effective | Delivered PT | Source certificate | Parcel | Allocated face\nCascade Pension Partners | 2022-11-09 | 2022-11-16 14:06 | CSC-NW-03-2022-0003 | NW-03 | 620000\nCascade Pension Partners | 2022-11-09 | 2022-11-16 14:06 | CSC-NW-02-2022-0002 | NW-02 | 520000\nCascade Pension Partners | 2022-11-09 | 2022-11-16 14:06 | CSC-NW-01-2022-0001 | NW-01 | 110000\nNorth Fork Energy Fund | 2022-11-21 | 2022-11-29 11:18 | CSC-NW-06-2022-0006 | NW-06 | 640000\nNorth Fork Energy Fund | 2022-11-21 | 2022-11-29 11:18 | CSC-NW-07-2022-0007 | NW-07 | 260000\nBlue River Capital | 2022-12-06 | 2022-12-14 09:42 | CSC-NW-04-2022-0004 | NW-04 | 580000\nBlue River Capital | 2022-12-06 | 2022-12-14 09:42 | CSC-NW-07-2022-0007 | NW-07 | 300000\nBlue River Capital | 2022-12-06 | 2022-12-14 09:42 | CSC-NW-05-2022-0005 | NW-05 | 220000\nPurchaser slices reference source certificates; this extract is not a new issuance or an eligibility determination. Other purchasers are excluded.\n')]),
        message('m7', 'm6', HANNAH, [TOM, CRAIG], '2023-08-17T10:20',
                "The references match the source copies in records. NW-07 is 560,000 total; the 260,000 and 300,000 slices exhaust it. NW-01 and NW-05 have remaining face outside these three purchases, so don't treat those buyer slices as the full parcel amounts.\n\nThe dates on the source certificates are issuance dates. The receipt and transmission entries in your register are later and shouldn't replace them on the source copies. CPP's missing page points to NW-01, whose source certificate was issued October 4. I can provide that source-reference page to Tom. This is a reference check; I haven't re-examined the acreage or the program screening.", kind='reply_all'),
        message('m8', 'm6', CRAIG, TOM, '2023-08-18T08:45',
                "I've attached the settlement bridge for these three agreements. Face is 3.25 million and cash is 2.932 million, before the Bellhaven and Alder fees. The fees are expenses paid from cash, not deductions from the face revenue line. All three delivery dates are in 2022.\n\nThat is only part of the 6.8 million annual recognized figure; don't label this the annual reconciliation. Across these three purchases, the four parcels on the May schedule allocate 2.4 million face, but buyer cash attributable to those slices differs by contract price. None of that tells us whether a whole parcel or only excess acreage would be affected. Please send each buyer only its own supporting entries.",
                attachments=[attachment('Three_purchase_settlement_bridge_2023-08-18.txt',
                    'CRAIG SATO — TRANSACTION SUPPORT — 18 August 2023\nAmounts in dollars. Three purchases only, not annual revenue reconciliation.\nBuyer | Face | Unit price | Cash funded | Bellhaven fee 6% of cash | Alder fee 8% of cash | Cash after both fees\nCPP | 1250000 | 0.90 | 1125000 | 67500 | 90000 | 967500\nNorth Fork | 900000 | 0.92 | 828000 | 49680 | 66240 | 712080\nBlue River | 1100000 | 0.89 | 979000 | 58740 | 78320 | 841940\nTOTAL | 3250000 | mixed | 2932000 | 175920 | 234560 | 2521520\nGross face recognized at certificate delivery under current policy; discounts affect cash; fees expensed.\nNo refund liability, disallowance finding, penalty, interest or reserve is calculated here.\n')]),
        message('m9', 'm7', TOM, ORR, '2023-08-18T14:10',
                "J — Hannah checked the source references and found your missing entry: 110,000 against NW-01, source certificate CSC-NW-01-2022-0001. Together with NW-03 and NW-02, that ties to the 1.25 million in your November 16 receipt. Attached is your allocation extract; it contains no other buyer's records.\n\nThe June pause stopped new placements. It wasn't a determination that your delivered credits were disallowed. We haven't received a determination on those credits that I can send you. I'm not asking your committee to accept the allocation list as fresh eligibility screening; it answers which source credits the delivery register says were allocated to you.", kind='forward', quote=False, keep_attachments=False, cc=[DEREK],
                attachments=[attachment('CPP_source_allocation_extract_2023-08-18.txt',
                    'CPP PURCHASE — ADMINISTRATOR SOURCE EXTRACT — 18 August 2023\nAgreement effective 9 November 2022; delivery register date 16 November 2022.\nCSC-NW-03-2022-0003 | NW-03 | 620000 face\nCSC-NW-02-2022-0002 | NW-02 | 520000 face\nCSC-NW-01-2022-0001 | NW-01 | 110000 face\nTotal 1250000 face. Source-reference reconciliation only; no new eligibility finding.\n')]),
        message('m10', 'm9', ORR, TOM, '2023-08-21T11:25',
                "Received; the missing reference is now in our committee file. That resolves the source-page question, not the eligibility question. We are still asking what screening was done for NW-03 before delivery and whether there is any later survey or county correspondence that changes the position.\n\nPlease preserve the versions of the checklist and deck actually supplied with our agreement. A current replacement deck would not answer what our committee reviewed last November. We aren't quantifying a tax loss or representing that the contractual disallowance trigger has occurred. We do want the Administrator to respond to the screening question and keep us updated when there is something substantive to report.", cc=[DEREK]),
    ], ['§1 gross face, cash discounts, fees [BINDING AUTHORING RULE]', '§2 disputed four face totals [ESTABLISHED in EMAIL-1462]',
        'CSC-CPA-BELLHAVEN executed buyer versions [EXISTING]', 'EX-028–035 source certificate numbers and issuance dates [EXISTING]',
        'Density expansion register §2 [AUTHORED FICTIONAL ALLOCATIONS AND RECEIPTS]'])

    write('THR-007', 'EMAIL-932', 'F', 1497,
          'Separate evidence of historical control performance from a narrow September remediation '
          'pilot on archived packets. A real test catches a reference error and finds unresolved '
          'support; its sign-off does not bless eligibility, authorize a restart, or prove old tests ran.', [
        message('m1', 'EMAIL-932', SARAH, MOSS, '2023-08-14T08:40',
                "Brenda — I'll send the remediation workplan separately from the historical record request. The calendars, quarterly packs and packet folders live in different locations; I'm preserving those locations rather than moving documents into a new 'testing' folder.\n\nFor the workplan, the first deliverable is a records test on a small archived sample: confirm the application version, recorded filing and acreage comparison can be traced from the packet index. That is narrower than deciding whether a credit qualifies. The broker-registration check will be a separate workstream. Could you tell me which fields you need in the sample record so the pilot produces something your team can inspect rather than another calendar entry?"),
        message('m2', 'm1', MOSS, SARAH, '2023-08-15T09:25',
                "For each selected packet, please record the population you selected from, selection method, application version/date, county recording reference, both acreage figures, reviewer and review date, plus the evidence for closing any exception. Preserve the first result when a document is corrected.\n\nA pilot on archived packets can show the new procedure operating in September. It cannot establish that the quarterly control operated in 2022 or earlier this year. We'll evaluate historical performance from dated workpapers and follow-up evidence for those periods. Also, please keep a missing document distinct from an acreage mismatch; a blank cell should not be treated as a match or an automatic eligibility failure."),
        message('m3', 'm2', SARAH, HANNAH, '2023-08-16T11:30',
                "Hannah — Brenda's suggested fields are below. I'd like to use NW-02, NW-04 and NW-07 for a records pilot, selected deliberately to cover a clean comparison, a known mismatch and an exhibit-reference question. This isn't a random sample or a basis for estimating a failure rate.\n\nPlease inventory those three packet folders as they stand. If an application copy lacks a transmittal stamp, record that rather than substituting the current tracker date. The original files stay where they are under the hold; working copies can go in the pilot folder with source paths. Tom can supply Alder records through the collection channel if needed, but please don't ask anyone to rewrite the historical packet.", kind='forward', keep_attachments=False),
        message('m4', 'm3', HANNAH, SARAH, '2023-08-17T14:15',
                "I've inventoried the copies. NW-02 has an application copy and recorded filing, both at 185 acres. NW-04 carries 340 on the application and 288 on the recorded filing. The NW-07 index points to a scan called Exhibit B, but the file behind that link is from a different folder; I'm checking the paper binder before assigning it a parcel.\n\nTwo application copies lack a filing stamp in the scan set. We have transmittal entries elsewhere, but I won't label these copies 'as filed' from that alone. I attached the source inventory with those qualifications. Please keep the pilot result separate from the county notice mapping question; the wrong link doesn't tell us which parcel the recorder's correction notice refers to.",
                attachments=[attachment('Pilot_source_inventory_2023-08-17.txt',
                    'RECORDS INVENTORY — 17 August 2023 — Hannah Cole\nPurposive archived sample: NW-02, NW-04, NW-07. Source files remain in place.\nNW-02 | application copy 185 ac | recorded filing 185 ac | comparison available\nNW-04 | application copy 340 ac | recorded filing 288 ac | difference 52 ac; reconciliation unresolved\nNW-07 | application copy 275 ac | recorded filing 231 ac | index exhibit link requires paper-binder check; difference 44 ac\nTwo application scans lack filing stamps. Transmittal entries do not alone authenticate as-filed contents.\nNo recorder notice is mapped by this inventory. No retrospective quarterly-control finding.\n')]),
        message('m5', 'm4', SARAH, HANNAH, '2023-08-18T10:35',
                "That's the distinction I need. Leave the mismatch entries open. For NW-07, save the incorrect index link and its current target before repairing the working-copy index. Record what the paper binder supplies, including the page count, so a reviewer can reproduce the change.\n\nI'll schedule the pilot for September 5 after the initial production work. Craig will be the second reviewer for the reference and arithmetic checks only. Neither of us will sign off eligibility from those checks. For the historical quarterly records, continue giving Alan source locations; the inventory you're preparing now should carry its current date even where the underlying documents are older.", cc=[CRAIG]),
        message('m6', 'm5', CRAIG, [SARAH, HANNAH], '2023-08-21T08:55',
                "I can do the second review on September 6. Please leave the first-pass findings visible rather than giving me only a cleaned-up packet. I'll check the source reference and recompute the differences, then sign the entries I actually reviewed.\n\nThe face builds in finance use claimed acreage. A records comparison is useful evidence for the review, but a 52-acre or 44-acre difference isn't a refund amount. We would need the applicable calculation and a decision about the scope of any disallowance before using it that way. The archived NW-04/NW-07 amounts should also stay out of the new Q4 held-file queue; those are different files.", kind='reply_all'),
        message('m7', 'm5', HANNAH, [SARAH, CRAIG], '2023-09-05T16:10',
                "The pilot first pass is done. NW-07's paper binder supplied the missing exhibit pages; the working-copy index now points to that copy, and the old link is retained in the change log. The recorded figure is still 231 against 275 on the application copy. Repairing the link did not reconcile the acreage.\n\nNW-02 ties at 185. NW-04 remains 340 against 288. The workpaper records which versions I used and which application scans weren't authenticated as filed. Attached is the first-pass extract for Craig's review tomorrow. This is a test of records we already held, not permission to restart placements or confirmation that an earlier sample was performed.", kind='reply_all',
                attachments=[attachment('Records_pilot_first_pass_2023-09-05.txt',
                    'ARCHIVED PACKET RECORDS PILOT — FIRST PASS — 5 September 2023\nSelection: purposive NW-02/NW-04/NW-07, three separate issue types; no statistical inference.\nReviewer: Hannah Cole. Second review pending.\nNW-02 | 185 vs 185 | difference 0 | reference comparison complete\nNW-04 | 340 vs 288 | difference 52 | substantive reconciliation open\nNW-07 | 275 vs 231 | difference 44 | exhibit index repaired from paper binder; substantive reconciliation open\nIndex change: saved original broken-link target; added paper-binder copy to working index only.\nApplication-copy authenticity limitations retained from 17 August inventory.\nNo eligibility clearance, historical control assurance, monetary loss or restart authorization.\n')]),
        message('m8', 'm7', CRAIG, [HANNAH, SARAH], '2023-09-06T11:45',
                "Second review completed this morning. I reproduced the three comparisons from the cited copies and checked the NW-07 index repair against the paper-binder copy. The arithmetic ties; the two substantive exceptions are still open.\n\nI've signed the reference-check section only. Please don't change the workpaper's overall status to passed because my signature is there. Sarah owns the follow-up; if Alder sends a reconciliation, it should have its own received date and source, with these first-pass results retained. For the auditor packet, use the workpaper and this review confirmation together. The calendar invite proves we scheduled the work, not what was tested.", kind='reply_all'),
        message('m9', 'm8', SARAH, MOSS, '2023-09-07T10:20',
                "Brenda — the archived-packet pilot ran September 5 with Craig's second review on September 6. Attached are the dated first-pass extract and the source inventory. The reference correction on NW-07 is complete; the NW-04 and NW-07 acreage reconciliations remain open. I've kept the initial findings intact.\n\nThis is the new remediation procedure operating on a purposive sample. We are not presenting it as the missing workpapers for the 2022 quarters or as a test of every packet. The original calendar and quarterly-pack materials are still being supplied by source location. Please let me know if the review confirmation needs to be in the same PBC item rather than filed as correspondence.", kind='forward', quote=False, keep_attachments=False,
                attachments=[{'from_doc': 'EMAIL-1500', 'filename': 'Pilot_source_inventory_2023-08-17.txt'},
                             {'from_doc': 'EMAIL-1503', 'filename': 'Records_pilot_first_pass_2023-09-05.txt'}]),
        message('m10', 'm9', MOSS, SARAH, '2023-09-08T09:40',
                "Please include Craig's dated confirmation in the same PBC item. We'll describe the scope as a three-packet remediation pilot, with one document-reference exception corrected and two acreage reconciliations still open. It isn't a clean operating-effectiveness conclusion on the program control.\n\nFor the next round, agree the sampling population before selection and name an owner and target date for each open exception. Keep the record of what you receive from Alder distinct from your assessment of it. Our request for the historical quarterly support remains separate. We also haven't reached a conclusion on the accounting contingency from these comparisons; that requires the broader management assessment and the ordinary audit inquiry process."),
    ], ['§0 / EMAIL-185–186 approved framework [ESTABLISHED]', '§6 / Arc F historical spot-check gap [OPEN BY DESIGN]',
        'EMAIL-203 remediation outline [ESTABLISHED]', '§2 acreage pairs [EXISTING AUTHORING MODEL / EX-020–027]',
        'Density expansion register §3 [AUTHORED SEPTEMBER PILOT]'])


if __name__ == '__main__':
    main()
